apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vb4ayj0xo-go-gitops
  description: This is GitOps manifest for vb4ayj0xo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: vb4ayj0xo-go
    backstage.io/kubernetes-id: vb4ayj0xo-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vb4ayj0xo-go
